---
- name: Install Docker on Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker.io
    - docker-compose

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

- name: Build Docker image
  docker_image:
    name: apache-test:1.3
    path: /CPE232_HOA11/docker
  register: result
  until: result is success


- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
